version: "3.8"

services:
  # Database Service
  db:
    image: postgres:15
    container_name: kbit_db
    restart: always
    environment:
      POSTGRES_USER: kashif
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Backend FastAPI Service
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: kbit_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_URL=postgresql://kashif:1234@db:5432/user_db
      - GROQ_API_KEY=${GROQ_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend  # Optional for hot reload in dev, ignore in prod

  # Frontend Nginx Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Pass the public IP/Domain of your server here later
        VITE_API_URL: http://localhost:8000
    container_name: kbit_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
